# Linear equation Interval methods

In [227]:
!pip install -q pyinterval

In [228]:
from interval import interval
from interval import imath
import pandas as pd
import numpy as np
import math

In [229]:
def calculate_width(x_i):
    return sum([x.sup - x.inf for x in x_i])

def calculate_midpoint(x_i):
    return (x_i[0].sup + x_i[0].inf) / 2

def itos(x_i):
    return f"[{x_i[0].inf:9.7f}, {x_i[0].sup:9.7f}]"

## Interval division

In [230]:
def interval_division(f, start, end, tol, tbl):
        X = interval[start, end]
        X_width = calculate_width(X)
        F = f(X)
        mid = calculate_midpoint(X)
        
        if 0 not in F: #Root not found
            tbl.loc[len(tbl)] = [itos(X), itos(F), X_width, mid, '',]
            return
        
        if X_width < e: #Root founded
            tbl.loc[len(tbl)] = [itos(X), itos(F), X_width, mid, 'Root']
            return
        
        tbl.loc[len(tbl)] = [itos(X), itos(F), X_width, mid, '']
        interval_division(f, start, mid, e, tbl)
        interval_division(f, mid, end, e, tbl)

In [231]:
func = lambda x: imath.sin(x-1)*(x-2)*(x-3)
e = 1e-2
a = 0.9
b = 2.3

In [232]:
result = pd.DataFrame(columns=['Interval', 'Interval extension', 'Width', 'Mid point', 'Root'])
interval_division(func, a, b, e, result)
result

,Interval,Interval extension,Width,Mid point,Root
0,"[0.9000000, 2.3000000]","[-0.6070417, 2.2258194]",1.400000,1.600000,
1,"[0.9000000, 1.6000000]","[-0.2306152, 1.3043241]",0.700000,1.250000,
2,"[0.9000000, 1.2500000]","[-0.2306152, 0.5715031]",0.350000,1.075000,
3,"[0.9000000, 1.0750000]","[-0.2306152, 0.1730876]",0.175000,0.987500,
4,"[0.9000000, 0.9875000]","[-0.2306152, -0.0254700]",0.087500,0.943750,
5,"[0.9875000, 1.0750000]","[-0.0254700, 0.1526810]",0.087500,1.031250,
6,"[0.9875000, 1.0312500]","[-0.0254700, 0.0636664]",0.043750,1.009375,
7,"[0.9875000, 1.0093750]","[-0.0254700, 0.0191027]",0.021875,0.998437,
8,"[0.9875000, 0.9984375]","[-0.0254700, -0.0031323]",0.010937,0.992969,
9,"[0.9984375, 1.0093750]","[-0.0031323, 0.0187937]",0.010937,1.003906,
10,"[0.9984375, 1.0039062]","[-0.0031323, 0.0078308]",0.005469,1.001172,Root
11,"[1.0039062, 1.0093750]","[0.0077030, 0.0186400]",0.005469,1.006641,
12,"[1.0093750, 1.0312500]","[0.0178800, 0.0616138]",0.021875,1.020312,
13,"[1.0312500, 1.0750000]","[0.0556355, 0.1429079]",0.043750,1.053125,
14,"[1.0750000, 1.2500000]","[0.0983452, 0.4405337]",0.175000,1.162500,
15,"[1.2500000, 1.6000000]","[0.1385462, 0.7410932]",0.350000,1.425000,
16,"[1.6000000, 2.3000000]","[-0.4046944, 0.5395926]",0.700000,1.950000,
17,"[1.6000000, 1.9500000]","[0.0296437, 0.4555127]",0.350000,1.775000,
18,"[1.9500000, 2.3000000]","[-0.3035208, 0.0505868]",0.350000,2.125000,
19,"[1.9500000, 2.1250000]","[-0.1184226, 0.0473690]",0.175000,2.037500,
20,"[1.9500000, 2.0375000]","[-0.0339072, 0.0452096]",0.087500,1.993750,
21,"[1.9500000, 1.9937500]","[0.0051156, 0.0439991]",0.043750,1.971875,
22,"[1.9937500, 2.0375000]","[-0.0324944, 0.0054157]",0.043750,2.015625,
23,"[1.9937500, 2.0156250]","[-0.0133613, 0.0053445]",0.021875,2.004687,
24,"[1.9937500, 2.0046875]","[-0.0039810, 0.0053079]",0.010938,1.999219,
25,"[1.9937500, 1.9992187]","[0.0006553, 0.0052894]",0.005469,1.996484,
26,"[1.9992187, 2.0046875]","[-0.0039593, 0.0006599]",0.005469,2.001953,Root
27,"[2.0046875, 2.0156250]","[-0.0132160, -0.0038944]",0.010937,2.010156,
28,"[2.0156250, 2.0375000]","[-0.0317880, -0.0127803]",0.021875,2.026562,
29,"[2.0375000, 2.1250000]","[-0.1085541, -0.0282560]",0.087500,2.081250,
30,"[2.1250000, 2.3000000]","[-0.2529340, -0.0789484]",0.175000,2.212500,